//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kh_ImprovDataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class FormEntry
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FormEntry()
        {
            this.Departments = new HashSet<Department>();
        }
    
        public int ID { get; set; }
        public string FormID { get; set; }
        public string SubjectLine { get; set; }
        public string CustomerName { get; set; }
        public string JobNumber { get; set; }
        public string DepartmentID { get; set; }
        public string ProblemMsg { get; set; }
        public string SuggestionMsg { get; set; }
        public System.DateTime DateEntered { get; set; }
        public bool IsAllEffected { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Department> Departments { get; set; }
    }
}
