//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("KhImprovement", "CustomerFormEntry", "Customer", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Kh_ImprovDataLayer.Customer), "FormEntry", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Kh_ImprovDataLayer.FormEntry))]
[assembly: EdmRelationshipAttribute("KhImprovement", "EmployeeFormEntry", "Employee", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Kh_ImprovDataLayer.Employee), "FormEntry", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Kh_ImprovDataLayer.FormEntry))]
[assembly: EdmRelationshipAttribute("KhImprovement", "DepartmentEmployee", "Department", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Kh_ImprovDataLayer.Department), "Employee", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Kh_ImprovDataLayer.Employee))]
[assembly: EdmRelationshipAttribute("KhImprovement", "DepartmentEffectedDept", "Department", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Kh_ImprovDataLayer.Department), "EffectedDept", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Kh_ImprovDataLayer.EffectedDept))]

#endregion

namespace Kh_ImprovDataLayer
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class KhImprovementContainer : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new KhImprovementContainer object using the connection string found in the 'KhImprovementContainer' section of the application configuration file.
        /// </summary>
        public KhImprovementContainer() : base("name=KhImprovementContainer", "KhImprovementContainer")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new KhImprovementContainer object.
        /// </summary>
        public KhImprovementContainer(string connectionString) : base(connectionString, "KhImprovementContainer")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new KhImprovementContainer object.
        /// </summary>
        public KhImprovementContainer(EntityConnection connection) : base(connection, "KhImprovementContainer")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<FormEntry> FormEntries
        {
            get
            {
                if ((_FormEntries == null))
                {
                    _FormEntries = base.CreateObjectSet<FormEntry>("FormEntries");
                }
                return _FormEntries;
            }
        }
        private ObjectSet<FormEntry> _FormEntries;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Employee> Employees
        {
            get
            {
                if ((_Employees == null))
                {
                    _Employees = base.CreateObjectSet<Employee>("Employees");
                }
                return _Employees;
            }
        }
        private ObjectSet<Employee> _Employees;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Department> Departments
        {
            get
            {
                if ((_Departments == null))
                {
                    _Departments = base.CreateObjectSet<Department>("Departments");
                }
                return _Departments;
            }
        }
        private ObjectSet<Department> _Departments;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Customer> Customers
        {
            get
            {
                if ((_Customers == null))
                {
                    _Customers = base.CreateObjectSet<Customer>("Customers");
                }
                return _Customers;
            }
        }
        private ObjectSet<Customer> _Customers;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<EffectedDept> EffectedDepts
        {
            get
            {
                if ((_EffectedDepts == null))
                {
                    _EffectedDepts = base.CreateObjectSet<EffectedDept>("EffectedDepts");
                }
                return _EffectedDepts;
            }
        }
        private ObjectSet<EffectedDept> _EffectedDepts;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the FormEntries EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToFormEntries(FormEntry formEntry)
        {
            base.AddObject("FormEntries", formEntry);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Employees EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToEmployees(Employee employee)
        {
            base.AddObject("Employees", employee);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Departments EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToDepartments(Department department)
        {
            base.AddObject("Departments", department);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Customers EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToCustomers(Customer customer)
        {
            base.AddObject("Customers", customer);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the EffectedDepts EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToEffectedDepts(EffectedDept effectedDept)
        {
            base.AddObject("EffectedDepts", effectedDept);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="KhImprovement", Name="Customer")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Customer : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Customer object.
        /// </summary>
        /// <param name="custID">Initial value of the CustID property.</param>
        public static Customer CreateCustomer(global::System.Int32 custID)
        {
            Customer customer = new Customer();
            customer.CustID = custID;
            return customer;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 CustID
        {
            get
            {
                return _CustID;
            }
            set
            {
                if (_CustID != value)
                {
                    OnCustIDChanging(value);
                    ReportPropertyChanging("CustID");
                    _CustID = StructuralObject.SetValidValue(value, "CustID");
                    ReportPropertyChanged("CustID");
                    OnCustIDChanged();
                }
            }
        }
        private global::System.Int32 _CustID;
        partial void OnCustIDChanging(global::System.Int32 value);
        partial void OnCustIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String CustomerName
        {
            get
            {
                return _CustomerName;
            }
            set
            {
                OnCustomerNameChanging(value);
                ReportPropertyChanging("CustomerName");
                _CustomerName = StructuralObject.SetValidValue(value, true, "CustomerName");
                ReportPropertyChanged("CustomerName");
                OnCustomerNameChanged();
            }
        }
        private global::System.String _CustomerName;
        partial void OnCustomerNameChanging(global::System.String value);
        partial void OnCustomerNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String JobNumber
        {
            get
            {
                return _JobNumber;
            }
            set
            {
                OnJobNumberChanging(value);
                ReportPropertyChanging("JobNumber");
                _JobNumber = StructuralObject.SetValidValue(value, true, "JobNumber");
                ReportPropertyChanged("JobNumber");
                OnJobNumberChanged();
            }
        }
        private global::System.String _JobNumber;
        partial void OnJobNumberChanging(global::System.String value);
        partial void OnJobNumberChanged();

        #endregion

        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("KhImprovement", "CustomerFormEntry", "FormEntry")]
        public EntityCollection<FormEntry> FormEntries
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<FormEntry>("KhImprovement.CustomerFormEntry", "FormEntry");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<FormEntry>("KhImprovement.CustomerFormEntry", "FormEntry", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="KhImprovement", Name="Department")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Department : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Department object.
        /// </summary>
        /// <param name="deptID">Initial value of the DeptID property.</param>
        /// <param name="deptName">Initial value of the DeptName property.</param>
        /// <param name="deptHead">Initial value of the DeptHead property.</param>
        public static Department CreateDepartment(global::System.Int32 deptID, global::System.String deptName, global::System.String deptHead)
        {
            Department department = new Department();
            department.DeptID = deptID;
            department.DeptName = deptName;
            department.DeptHead = deptHead;
            return department;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 DeptID
        {
            get
            {
                return _DeptID;
            }
            set
            {
                if (_DeptID != value)
                {
                    OnDeptIDChanging(value);
                    ReportPropertyChanging("DeptID");
                    _DeptID = StructuralObject.SetValidValue(value, "DeptID");
                    ReportPropertyChanged("DeptID");
                    OnDeptIDChanged();
                }
            }
        }
        private global::System.Int32 _DeptID;
        partial void OnDeptIDChanging(global::System.Int32 value);
        partial void OnDeptIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String DeptName
        {
            get
            {
                return _DeptName;
            }
            set
            {
                OnDeptNameChanging(value);
                ReportPropertyChanging("DeptName");
                _DeptName = StructuralObject.SetValidValue(value, false, "DeptName");
                ReportPropertyChanged("DeptName");
                OnDeptNameChanged();
            }
        }
        private global::System.String _DeptName;
        partial void OnDeptNameChanging(global::System.String value);
        partial void OnDeptNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String DeptHead
        {
            get
            {
                return _DeptHead;
            }
            set
            {
                OnDeptHeadChanging(value);
                ReportPropertyChanging("DeptHead");
                _DeptHead = StructuralObject.SetValidValue(value, false, "DeptHead");
                ReportPropertyChanged("DeptHead");
                OnDeptHeadChanged();
            }
        }
        private global::System.String _DeptHead;
        partial void OnDeptHeadChanging(global::System.String value);
        partial void OnDeptHeadChanged();

        #endregion

        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("KhImprovement", "DepartmentEmployee", "Employee")]
        public EntityCollection<Employee> Employees
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Employee>("KhImprovement.DepartmentEmployee", "Employee");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Employee>("KhImprovement.DepartmentEmployee", "Employee", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("KhImprovement", "DepartmentEffectedDept", "EffectedDept")]
        public EntityCollection<EffectedDept> EffectedDepts
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<EffectedDept>("KhImprovement.DepartmentEffectedDept", "EffectedDept");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<EffectedDept>("KhImprovement.DepartmentEffectedDept", "EffectedDept", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="KhImprovement", Name="EffectedDept")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class EffectedDept : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new EffectedDept object.
        /// </summary>
        /// <param name="id">Initial value of the ID property.</param>
        public static EffectedDept CreateEffectedDept(global::System.Int32 id)
        {
            EffectedDept effectedDept = new EffectedDept();
            effectedDept.ID = id;
            return effectedDept;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value, "ID");
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int32 _ID;
        partial void OnIDChanging(global::System.Int32 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String EffectDept1
        {
            get
            {
                return _EffectDept1;
            }
            set
            {
                OnEffectDept1Changing(value);
                ReportPropertyChanging("EffectDept1");
                _EffectDept1 = StructuralObject.SetValidValue(value, true, "EffectDept1");
                ReportPropertyChanged("EffectDept1");
                OnEffectDept1Changed();
            }
        }
        private global::System.String _EffectDept1;
        partial void OnEffectDept1Changing(global::System.String value);
        partial void OnEffectDept1Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String EffectDept2
        {
            get
            {
                return _EffectDept2;
            }
            set
            {
                OnEffectDept2Changing(value);
                ReportPropertyChanging("EffectDept2");
                _EffectDept2 = StructuralObject.SetValidValue(value, true, "EffectDept2");
                ReportPropertyChanged("EffectDept2");
                OnEffectDept2Changed();
            }
        }
        private global::System.String _EffectDept2;
        partial void OnEffectDept2Changing(global::System.String value);
        partial void OnEffectDept2Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String EffectDept3
        {
            get
            {
                return _EffectDept3;
            }
            set
            {
                OnEffectDept3Changing(value);
                ReportPropertyChanging("EffectDept3");
                _EffectDept3 = StructuralObject.SetValidValue(value, true, "EffectDept3");
                ReportPropertyChanged("EffectDept3");
                OnEffectDept3Changed();
            }
        }
        private global::System.String _EffectDept3;
        partial void OnEffectDept3Changing(global::System.String value);
        partial void OnEffectDept3Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String EffectDept4
        {
            get
            {
                return _EffectDept4;
            }
            set
            {
                OnEffectDept4Changing(value);
                ReportPropertyChanging("EffectDept4");
                _EffectDept4 = StructuralObject.SetValidValue(value, true, "EffectDept4");
                ReportPropertyChanged("EffectDept4");
                OnEffectDept4Changed();
            }
        }
        private global::System.String _EffectDept4;
        partial void OnEffectDept4Changing(global::System.String value);
        partial void OnEffectDept4Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String EffectDept5
        {
            get
            {
                return _EffectDept5;
            }
            set
            {
                OnEffectDept5Changing(value);
                ReportPropertyChanging("EffectDept5");
                _EffectDept5 = StructuralObject.SetValidValue(value, true, "EffectDept5");
                ReportPropertyChanged("EffectDept5");
                OnEffectDept5Changed();
            }
        }
        private global::System.String _EffectDept5;
        partial void OnEffectDept5Changing(global::System.String value);
        partial void OnEffectDept5Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String EffectDept6
        {
            get
            {
                return _EffectDept6;
            }
            set
            {
                OnEffectDept6Changing(value);
                ReportPropertyChanging("EffectDept6");
                _EffectDept6 = StructuralObject.SetValidValue(value, true, "EffectDept6");
                ReportPropertyChanged("EffectDept6");
                OnEffectDept6Changed();
            }
        }
        private global::System.String _EffectDept6;
        partial void OnEffectDept6Changing(global::System.String value);
        partial void OnEffectDept6Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String EffectDept7
        {
            get
            {
                return _EffectDept7;
            }
            set
            {
                OnEffectDept7Changing(value);
                ReportPropertyChanging("EffectDept7");
                _EffectDept7 = StructuralObject.SetValidValue(value, true, "EffectDept7");
                ReportPropertyChanged("EffectDept7");
                OnEffectDept7Changed();
            }
        }
        private global::System.String _EffectDept7;
        partial void OnEffectDept7Changing(global::System.String value);
        partial void OnEffectDept7Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String EffectDept8
        {
            get
            {
                return _EffectDept8;
            }
            set
            {
                OnEffectDept8Changing(value);
                ReportPropertyChanging("EffectDept8");
                _EffectDept8 = StructuralObject.SetValidValue(value, true, "EffectDept8");
                ReportPropertyChanged("EffectDept8");
                OnEffectDept8Changed();
            }
        }
        private global::System.String _EffectDept8;
        partial void OnEffectDept8Changing(global::System.String value);
        partial void OnEffectDept8Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String EffectDept9
        {
            get
            {
                return _EffectDept9;
            }
            set
            {
                OnEffectDept9Changing(value);
                ReportPropertyChanging("EffectDept9");
                _EffectDept9 = StructuralObject.SetValidValue(value, true, "EffectDept9");
                ReportPropertyChanged("EffectDept9");
                OnEffectDept9Changed();
            }
        }
        private global::System.String _EffectDept9;
        partial void OnEffectDept9Changing(global::System.String value);
        partial void OnEffectDept9Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String EffectDept10
        {
            get
            {
                return _EffectDept10;
            }
            set
            {
                OnEffectDept10Changing(value);
                ReportPropertyChanging("EffectDept10");
                _EffectDept10 = StructuralObject.SetValidValue(value, true, "EffectDept10");
                ReportPropertyChanged("EffectDept10");
                OnEffectDept10Changed();
            }
        }
        private global::System.String _EffectDept10;
        partial void OnEffectDept10Changing(global::System.String value);
        partial void OnEffectDept10Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String EffectDept11
        {
            get
            {
                return _EffectDept11;
            }
            set
            {
                OnEffectDept11Changing(value);
                ReportPropertyChanging("EffectDept11");
                _EffectDept11 = StructuralObject.SetValidValue(value, true, "EffectDept11");
                ReportPropertyChanged("EffectDept11");
                OnEffectDept11Changed();
            }
        }
        private global::System.String _EffectDept11;
        partial void OnEffectDept11Changing(global::System.String value);
        partial void OnEffectDept11Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String EffectDept12
        {
            get
            {
                return _EffectDept12;
            }
            set
            {
                OnEffectDept12Changing(value);
                ReportPropertyChanging("EffectDept12");
                _EffectDept12 = StructuralObject.SetValidValue(value, true, "EffectDept12");
                ReportPropertyChanged("EffectDept12");
                OnEffectDept12Changed();
            }
        }
        private global::System.String _EffectDept12;
        partial void OnEffectDept12Changing(global::System.String value);
        partial void OnEffectDept12Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String EffectDept13
        {
            get
            {
                return _EffectDept13;
            }
            set
            {
                OnEffectDept13Changing(value);
                ReportPropertyChanging("EffectDept13");
                _EffectDept13 = StructuralObject.SetValidValue(value, true, "EffectDept13");
                ReportPropertyChanged("EffectDept13");
                OnEffectDept13Changed();
            }
        }
        private global::System.String _EffectDept13;
        partial void OnEffectDept13Changing(global::System.String value);
        partial void OnEffectDept13Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String EffectDept14
        {
            get
            {
                return _EffectDept14;
            }
            set
            {
                OnEffectDept14Changing(value);
                ReportPropertyChanging("EffectDept14");
                _EffectDept14 = StructuralObject.SetValidValue(value, true, "EffectDept14");
                ReportPropertyChanged("EffectDept14");
                OnEffectDept14Changed();
            }
        }
        private global::System.String _EffectDept14;
        partial void OnEffectDept14Changing(global::System.String value);
        partial void OnEffectDept14Changed();

        #endregion

        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("KhImprovement", "DepartmentEffectedDept", "Department")]
        public Department Department
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Department>("KhImprovement.DepartmentEffectedDept", "Department").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Department>("KhImprovement.DepartmentEffectedDept", "Department").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Department> DepartmentReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Department>("KhImprovement.DepartmentEffectedDept", "Department");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Department>("KhImprovement.DepartmentEffectedDept", "Department", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="KhImprovement", Name="Employee")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Employee : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Employee object.
        /// </summary>
        /// <param name="empID">Initial value of the EmpID property.</param>
        public static Employee CreateEmployee(global::System.Int32 empID)
        {
            Employee employee = new Employee();
            employee.EmpID = empID;
            return employee;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 EmpID
        {
            get
            {
                return _EmpID;
            }
            set
            {
                if (_EmpID != value)
                {
                    OnEmpIDChanging(value);
                    ReportPropertyChanging("EmpID");
                    _EmpID = StructuralObject.SetValidValue(value, "EmpID");
                    ReportPropertyChanged("EmpID");
                    OnEmpIDChanged();
                }
            }
        }
        private global::System.Int32 _EmpID;
        partial void OnEmpIDChanging(global::System.Int32 value);
        partial void OnEmpIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String FirstName
        {
            get
            {
                return _FirstName;
            }
            set
            {
                OnFirstNameChanging(value);
                ReportPropertyChanging("FirstName");
                _FirstName = StructuralObject.SetValidValue(value, true, "FirstName");
                ReportPropertyChanged("FirstName");
                OnFirstNameChanged();
            }
        }
        private global::System.String _FirstName;
        partial void OnFirstNameChanging(global::System.String value);
        partial void OnFirstNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String LastName
        {
            get
            {
                return _LastName;
            }
            set
            {
                OnLastNameChanging(value);
                ReportPropertyChanging("LastName");
                _LastName = StructuralObject.SetValidValue(value, true, "LastName");
                ReportPropertyChanged("LastName");
                OnLastNameChanged();
            }
        }
        private global::System.String _LastName;
        partial void OnLastNameChanging(global::System.String value);
        partial void OnLastNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Email
        {
            get
            {
                return _Email;
            }
            set
            {
                OnEmailChanging(value);
                ReportPropertyChanging("Email");
                _Email = StructuralObject.SetValidValue(value, true, "Email");
                ReportPropertyChanged("Email");
                OnEmailChanged();
            }
        }
        private global::System.String _Email;
        partial void OnEmailChanging(global::System.String value);
        partial void OnEmailChanged();

        #endregion

        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("KhImprovement", "EmployeeFormEntry", "FormEntry")]
        public EntityCollection<FormEntry> FormEntries
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<FormEntry>("KhImprovement.EmployeeFormEntry", "FormEntry");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<FormEntry>("KhImprovement.EmployeeFormEntry", "FormEntry", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("KhImprovement", "DepartmentEmployee", "Department")]
        public Department Department
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Department>("KhImprovement.DepartmentEmployee", "Department").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Department>("KhImprovement.DepartmentEmployee", "Department").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Department> DepartmentReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Department>("KhImprovement.DepartmentEmployee", "Department");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Department>("KhImprovement.DepartmentEmployee", "Department", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="KhImprovement", Name="FormEntry")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class FormEntry : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new FormEntry object.
        /// </summary>
        /// <param name="formID">Initial value of the FormID property.</param>
        /// <param name="department">Initial value of the Department property.</param>
        /// <param name="problemMsg">Initial value of the ProblemMsg property.</param>
        /// <param name="suggestionMsg">Initial value of the SuggestionMsg property.</param>
        /// <param name="dateEntered">Initial value of the DateEntered property.</param>
        /// <param name="isAllDept">Initial value of the IsAllDept property.</param>
        public static FormEntry CreateFormEntry(global::System.Int32 formID, global::System.String department, global::System.String problemMsg, global::System.String suggestionMsg, global::System.DateTime dateEntered, global::System.Boolean isAllDept)
        {
            FormEntry formEntry = new FormEntry();
            formEntry.FormID = formID;
            formEntry.Department = department;
            formEntry.ProblemMsg = problemMsg;
            formEntry.SuggestionMsg = suggestionMsg;
            formEntry.DateEntered = dateEntered;
            formEntry.IsAllDept = isAllDept;
            return formEntry;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 FormID
        {
            get
            {
                return _FormID;
            }
            set
            {
                if (_FormID != value)
                {
                    OnFormIDChanging(value);
                    ReportPropertyChanging("FormID");
                    _FormID = StructuralObject.SetValidValue(value, "FormID");
                    ReportPropertyChanged("FormID");
                    OnFormIDChanged();
                }
            }
        }
        private global::System.Int32 _FormID;
        partial void OnFormIDChanging(global::System.Int32 value);
        partial void OnFormIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Department
        {
            get
            {
                return _Department;
            }
            set
            {
                OnDepartmentChanging(value);
                ReportPropertyChanging("Department");
                _Department = StructuralObject.SetValidValue(value, false, "Department");
                ReportPropertyChanged("Department");
                OnDepartmentChanged();
            }
        }
        private global::System.String _Department;
        partial void OnDepartmentChanging(global::System.String value);
        partial void OnDepartmentChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String CustomerName
        {
            get
            {
                return _CustomerName;
            }
            set
            {
                OnCustomerNameChanging(value);
                ReportPropertyChanging("CustomerName");
                _CustomerName = StructuralObject.SetValidValue(value, true, "CustomerName");
                ReportPropertyChanged("CustomerName");
                OnCustomerNameChanged();
            }
        }
        private global::System.String _CustomerName;
        partial void OnCustomerNameChanging(global::System.String value);
        partial void OnCustomerNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String JobNumber
        {
            get
            {
                return _JobNumber;
            }
            set
            {
                OnJobNumberChanging(value);
                ReportPropertyChanging("JobNumber");
                _JobNumber = StructuralObject.SetValidValue(value, true, "JobNumber");
                ReportPropertyChanged("JobNumber");
                OnJobNumberChanged();
            }
        }
        private global::System.String _JobNumber;
        partial void OnJobNumberChanging(global::System.String value);
        partial void OnJobNumberChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String SubjectLine
        {
            get
            {
                return _SubjectLine;
            }
            set
            {
                OnSubjectLineChanging(value);
                ReportPropertyChanging("SubjectLine");
                _SubjectLine = StructuralObject.SetValidValue(value, true, "SubjectLine");
                ReportPropertyChanged("SubjectLine");
                OnSubjectLineChanged();
            }
        }
        private global::System.String _SubjectLine;
        partial void OnSubjectLineChanging(global::System.String value);
        partial void OnSubjectLineChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String ProblemMsg
        {
            get
            {
                return _ProblemMsg;
            }
            set
            {
                OnProblemMsgChanging(value);
                ReportPropertyChanging("ProblemMsg");
                _ProblemMsg = StructuralObject.SetValidValue(value, false, "ProblemMsg");
                ReportPropertyChanged("ProblemMsg");
                OnProblemMsgChanged();
            }
        }
        private global::System.String _ProblemMsg;
        partial void OnProblemMsgChanging(global::System.String value);
        partial void OnProblemMsgChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String SuggestionMsg
        {
            get
            {
                return _SuggestionMsg;
            }
            set
            {
                OnSuggestionMsgChanging(value);
                ReportPropertyChanging("SuggestionMsg");
                _SuggestionMsg = StructuralObject.SetValidValue(value, false, "SuggestionMsg");
                ReportPropertyChanged("SuggestionMsg");
                OnSuggestionMsgChanged();
            }
        }
        private global::System.String _SuggestionMsg;
        partial void OnSuggestionMsgChanging(global::System.String value);
        partial void OnSuggestionMsgChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime DateEntered
        {
            get
            {
                return _DateEntered;
            }
            set
            {
                OnDateEnteredChanging(value);
                ReportPropertyChanging("DateEntered");
                _DateEntered = StructuralObject.SetValidValue(value, "DateEntered");
                ReportPropertyChanged("DateEntered");
                OnDateEnteredChanged();
            }
        }
        private global::System.DateTime _DateEntered;
        partial void OnDateEnteredChanging(global::System.DateTime value);
        partial void OnDateEnteredChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean IsAllDept
        {
            get
            {
                return _IsAllDept;
            }
            set
            {
                OnIsAllDeptChanging(value);
                ReportPropertyChanging("IsAllDept");
                _IsAllDept = StructuralObject.SetValidValue(value, "IsAllDept");
                ReportPropertyChanged("IsAllDept");
                OnIsAllDeptChanged();
            }
        }
        private global::System.Boolean _IsAllDept;
        partial void OnIsAllDeptChanging(global::System.Boolean value);
        partial void OnIsAllDeptChanged();

        #endregion

        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("KhImprovement", "CustomerFormEntry", "Customer")]
        public Customer Customer
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Customer>("KhImprovement.CustomerFormEntry", "Customer").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Customer>("KhImprovement.CustomerFormEntry", "Customer").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Customer> CustomerReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Customer>("KhImprovement.CustomerFormEntry", "Customer");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Customer>("KhImprovement.CustomerFormEntry", "Customer", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("KhImprovement", "EmployeeFormEntry", "Employee")]
        public Employee Employee
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Employee>("KhImprovement.EmployeeFormEntry", "Employee").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Employee>("KhImprovement.EmployeeFormEntry", "Employee").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Employee> EmployeeReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Employee>("KhImprovement.EmployeeFormEntry", "Employee");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Employee>("KhImprovement.EmployeeFormEntry", "Employee", value);
                }
            }
        }

        #endregion

    }

    #endregion

}
